version: '3.7'

services: 
  elasticsearch:
    image: elasticsearch:6.4.1
    container_name: elasticsearch
    ports: ['9200:9200']
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks: [monitor]
  kibana:
    image: kibana:6.4.1
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks: [monitor]
  logstash:
    build: ./logstash
    container_name: logstash
    networks: ['monitor']
    depends_on: ['elasticsearch']
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5
  nginx:
    build: ./nginx
    ports: ['8080:80']
    networks: ['monitor']
    volumes:
      - ./nginx/data:/var/www/html
    depends_on: 
      - logstash

networks:
  monitor: