version: '3.7'

services: 
  elasticsearch:
    image: elasticsearch:6.4.1
    container_name: elasticsearch
    ports: ['9200:9200']
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks: [monitor]
  kibana:
    image: kibana:6.4.1
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks: [monitor]
  logstash:
    image: logstash:5.6.12
    container_name: logstash
    networks: ['monitor']
    depends_on: ['elasticsearch']
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5
  nginx:
    image: nginx:1.14
    ports: ['80:80']
    networks: ['monitor']
    volumes:
      - ./nginx:/

networks:
  monitor: